DROP VIEW AWUNADM.N_UNTARTAB;
DROP VIEW AWUNADM.GEN_ITM_TAX;


CREATE OR REPLACE FORCE VIEW AWUNADM.GEN_ITM_TAX
(
   INSTANCEID,
   TAR_HSC_NB1,
   TAR_HSC_NB2,
   TAR_PRF,
   TAR_PRC_EXT,
   VIT_WGT_NET,
   VIT_CIF,
   TAR_PRC_NAT,
   IDE_RCP_DAT,
   IDE_TYP_PRC,
   VGS_INV_CUR_RAT,
   TAX_LIN_COD,
   TAX_LIN_AMT,
   TAX_LIN_BSE,
   TAX_LIN_RAT,
   TAX_AMT,
   KEY_ITM_NBR,
   N_H6
)
AS
   SELECT ALL
          AWUNADM.SAD_ITEM.INSTANCEID,
          AWUNADM.SAD_ITEM.TAR_HSC_NB1,
          AWUNADM.SAD_ITEM.TAR_HSC_NB2,
          AWUNADM.SAD_ITEM.TAR_PRF,
          AWUNADM.SAD_ITEM.TAR_PRC_EXT,
          AWUNADM.SAD_ITEM.VIT_WGT_NET,
          AWUNADM.SAD_ITEM.VIT_CIF,
          AWUNADM.SAD_ITEM.TAR_PRC_NAT,
          AWUNADM.SAD_GENERAL_SEGMENT.IDE_RCP_DAT,
          SAD_GENERAL_SEGMENT.IDE_TYP_PRC,
          SAD_GENERAL_SEGMENT.VGS_INV_CUR_RAT,
          AWUNADM.SAD_TAX.TAX_LIN_COD,
          AWUNADM.SAD_TAX.TAX_LIN_AMT,
          AWUNADM.SAD_TAX.TAX_LIN_BSE,
          AWUNADM.SAD_TAX.TAX_LIN_RAT,
          AWUNADM.SAD_ITEM.TAX_AMT,
          AWUNADM.SAD_ITEM.KEY_ITM_NBR,
          AWUNADM.SAD_ITEM.TAR_HSC_NB1 || AWUNADM.SAD_ITEM.TAR_HSC_NB2 N_H6
     FROM AWUNADM.SAD_GENERAL_SEGMENT, AWUNADM.SAD_ITEM, AWUNADM.SAD_TAX
    WHERE     (    AWUNADM.SAD_GENERAL_SEGMENT.IDE_TYP_PRC = 4
               AND AWUNADM.SAD_GENERAL_SEGMENT.IDE_REG_NBR IS NOT NULL
               AND AWUNADM.SAD_GENERAL_SEGMENT.IDE_REG_SER IS NOT NULL 
                                                                      )
          AND (    (AWUNADM.SAD_GENERAL_SEGMENT.INSTANCEID =
                       AWUNADM.SAD_ITEM.INSTANCEID(+))
               AND (AWUNADM.SAD_ITEM.INSTANCEID =
                       AWUNADM.SAD_TAX.INSTANCEID(+))
               AND (AWUNADM.SAD_ITEM.KEY_ITM_NBR =
                       AWUNADM.SAD_TAX.KEY_ITM_NBR(+)));

CREATE OR REPLACE FORCE VIEW AWUNADM.N_UNTARTAB
(
   HS6_COD,
   TAR_PR1,
   TAR_PR2,
   TAR_T01,
   TAR_T02,
   TAR_T03,
   VALID_TO,
   N_T_H6
)
AS
   SELECT ALL
          AWUNADM.UNTARTAB.HS6_COD,
          AWUNADM.UNTARTAB.TAR_PR1,
          AWUNADM.UNTARTAB.TAR_PR2,
          AWUNADM.UNTARTAB.TAR_T01,
          AWUNADM.UNTARTAB.TAR_T02,
          AWUNADM.UNTARTAB.TAR_T03,
          AWUNADM.UNTARTAB.VALID_TO,
             AWUNADM.UNTARTAB.HS6_COD
          || AWUNADM.UNTARTAB.TAR_PR1
          || AWUNADM.UNTARTAB.TAR_PR2
             N_T_H6
     FROM AWUNADM.UNTARTAB;
